trigger: none

schedules:
- cron: "08 10 * * *" 
  displayName: 'Changing name'
  branches:
     include:
     - main
     - VS_build
  always: true

pool:
  vmImage: ubuntu-latest

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARM_APXDEMO'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # install powershell 
      Install-Module -Name Az -Repository PSGallery -Force
      # Set the VM name and resource group name
      $vmName = "UbuntuRunningDemoVM"
      $resourceGroup = "ApxDemo"
      
      echo $vmName
      echo $resourceGroup
      
      $powerState = az vm show --name $vmName --resource-group $resourceGroup --show-details --query powerState --output table
      
      echo $powerState
      
      
      # Check the power state and take action accordingly
      if ($powerState -eq "VM running") {
          Write-Output "VM is running. Stopping the VM..."
          echo $vmName
          az vm deallocate --name $vmName --resource-group $resourceGroup --no-wait
      }
      elseif ($powerState -eq "VM deallocated" -or $powerState -eq "VM stopped") {
          Write-Output "VM is deallocated or stopped. Starting the VM..."
          az vm start --name $vmName --resource-group $resourceGroup --no-wait
      }
      else {
          Write-Output "Unknown power state: $powerState"
      }